version: "3.9"
services:
  phpmotors-app:
    container_name: "phpmotors"
    build: 
      context: .
      dockerfile: ./Dockerfile.phpmotors
    # image: "php:7.3-apache"
    volumes:
      - ".:/var/www/html"
    ports:
      - "1234:80"
    depends_on:
      - "mysql"
    environment:
      - "DOCKER=true"
  mysql:
    container_name: "phpmotors-mysql"
    # image: "mysql:8.0.26"
    build:
      context: .
      dockerfile: ./Dockerfile.db
    command: "--default-authentication-plugin=mysql_native_password"
    environment:
      - "MYSQL_ROOT_PASSWORD=some_password"
    restart: always